### ISSUE TITLE
default sorting does not allow multiple fields

### ISSUE THREAD

**Issue by anho** [ongr-io/FilterManagerBundle#161]
Hi,

unfortunately there is no possibility to define multiple fields for the default sorting like this:

```
ongr_filter_manager:
  filters:
    sort:
      sorting:
        request_field: 'sort'
        choices:
          - key: score
            label: filters.sort.best_match
            fields:
              - { field: foo, order: asc }
              - { field: _score, order: desc }
            default: true
```

It would be great if you can add that.
