### ISSUE TITLE
Handle nested fields

### ISSUE THREAD

**Issue by tautrimas** [ongr-io/FilterManagerBundle#172]
Nested field support can be added like this:

```yaml
project_foo.widget.title:
    class: NestedMatchSearch
    calls:
            - [setRequestField, ['q']]
            - [setField, ['title,my_object.path+variants.title']]
```

```php
/**
 * Improved match search with nested search capability.
 */
class NestedMatchSearch extends MatchSearch
{
    /**
     * {@inheritdoc}
     */
    public function modifySearch(Search $search, FilterState $state = null, SearchRequest $request = null)
    {
        if ($state && $state->isActive()) {
            if (strpos($this->getField(), ',') !== false) {
                $subQuery = new BoolQuery();
                foreach (explode(',', $this->getField()) as $field) {
                    $subQuery->add($this->buildMatchPart($field, $state), 'should');
                }
                $search->addQuery($subQuery, 'must');
            } else {
                $search->addQuery($this->buildMatchPart($this->getField(), $state), 'must');
            }
        }
    }

    /**
     * Build possibly nested match part.
     *
     * @param string      $field
     * @param FilterState $state
     *
     * @return BuilderInterface
     */
    private function buildMatchPart($field, FilterState $state)
    {
        if (false === strpos($field, '+')) {
            return new MatchQuery($field, $state->getValue());
        } else {
            list ($path, $fieldName) = explode('+', $field);

            return new NestedQuery($path, new MatchQuery($fieldName, $state->getValue()));
        }
    }
}
```

Code is from 0.5.10 branch, so feature conflicts exist.
