### ISSUE TITLE
Error in the documentation for sort filters

### ISSUE THREAD

**Issue by DennisBM** [ongr-io/FilterManagerBundle#239]
Hey guys,

you got a small error in your documentation for the sort filter. The configuration example is missing the `options` field before the `choices`.

Should look like this:
```
# app/config/config.yml
    
ongr_filter_manager:
    # ...
    filters:
        search_sort:
            type: sort
            request_field: sort
            document_field: ~
            options:
                choices:
                    # single field sorting
                    stock_asc: { field: stock, default: true, order: asc }
                    stock_desc: { field: stock, order: desc }
                    # molti field sorting
                    price_desc_hits_desc: 
                        fields: 
                            - {field: price, order: desc}
                            - {field: hits, order: desc}
                    price_desc_hits_asc:
                        fields:
                            - {field: price, order: desc}
                            - {field: hits, order: asc}
```
