### ISSUE TITLE
Custom filter does not work

### ISSUE THREAD

**Issue by norkunas** [ongr-io/FilterManagerBundle#54]
I have tried to register custom filter like:

```yaml
wdn_search.filters.wdn_match:
    class: WDN\SearchBundle\Filters\WDNMatchSearch
    arguments: ["search", "search"]
    tags:
        - { name: ongr_filter_manager.filter, manager: profile_list, filter_name: wdn_match }
```

```php
<?php
namespace WDN\SearchBundle\Filters;

use ONGR\FilterManagerBundle\Filters\Widget\Search\MatchSearch;

class WDNMatchSearch extends MatchSearch
{
    public function __construct($requestField, $field)
    {
        $this->setRequestField($requestField);
        $this->setField($field);
    }
}

```

But then i ran into the problems when setting that filter to work:
```
ongr_filter_manager:
    managers:
        profile_list:
            filters:
                - wdn_match
                - visible
            repository: 'es.manager.default.profile'
    filters:
        match:
            visible:
                request_field: 'visible'
                field: visible
```
I get error:
```
ServiceNotFoundException in CheckExceptionOnInvalidReferenceBehaviorPass.php line 58:
The service "ongr_filter_manager.profile_list" has a dependency on a non-existent service "ongr_filter_manager.filter.wdn_match".
```

If i don't include the filter in list then i get results, but the filter is not applied (request url /searchtest?visible=true&search=somestring):
```
int(10)
array(2) {
  ["visibility"]=>
  object(ONGR\FilterManagerBundle\Filters\ViewData)#8209 (4) {
    ["state":"ONGR\FilterManagerBundle\Filters\ViewData":private]=>
    object(ONGR\FilterManagerBundle\Filters\FilterState)#8174 (4) {
      ["active":"ONGR\FilterManagerBundle\Filters\FilterState":private]=>
      bool(true)
      ["value":"ONGR\FilterManagerBundle\Filters\FilterState":private]=>
      string(4) "true"
      ["urlParameters":"ONGR\FilterManagerBundle\Filters\FilterState":private]=>
      array(1) {
        ["visible"]=>
        string(4) "true"
      }
      ["name":"ONGR\FilterManagerBundle\Filters\FilterState":private]=>
      string(10) "visibility"
    }
    ["urlParameters":"ONGR\FilterManagerBundle\Filters\ViewData":private]=>
    array(1) {
      ["visible"]=>
      string(4) "true"
    }
    ["resetUrlParameters":"ONGR\FilterManagerBundle\Filters\ViewData":private]=>
    array(0) {
    }
    ["name":"ONGR\FilterManagerBundle\Filters\ViewData":private]=>
    string(10) "visibility"
  }
  ["wdn_match"]=>
  object(ONGR\FilterManagerBundle\Filters\ViewData)#8215 (4) {
    ["state":"ONGR\FilterManagerBundle\Filters\ViewData":private]=>
    object(ONGR\FilterManagerBundle\Filters\FilterState)#8175 (4) {
      ["active":"ONGR\FilterManagerBundle\Filters\FilterState":private]=>
      bool(false)
      ["value":"ONGR\FilterManagerBundle\Filters\FilterState":private]=>
      NULL
      ["urlParameters":"ONGR\FilterManagerBundle\Filters\FilterState":private]=>
      array(0) {
      }
      ["name":"ONGR\FilterManagerBundle\Filters\FilterState":private]=>
      string(9) "wdn_match"
    }
    ["urlParameters":"ONGR\FilterManagerBundle\Filters\ViewData":private]=>
    array(1) {
      ["visible"]=>
      string(4) "true"
    }
    ["resetUrlParameters":"ONGR\FilterManagerBundle\Filters\ViewData":private]=>
    array(1) {
      ["visible"]=>
      string(4) "true"
    }
    ["name":"ONGR\FilterManagerBundle\Filters\ViewData":private]=>
    string(9) "wdn_match"
  }
}
```

Route config:
```yaml
wdn_profile_search:
    pattern: /searchtest
    methods: [GET]
    defaults:
        _controller: WDNSearchBundle:Company:test
        managerName: profile_list
```

Is there anything i don't understand or it's a bug?
